version: '3'

services:
  website:
    build: ./website
    environment:
      - VIRTUAL_HOST=domain2.tld
      - LETSENCRYPT_HOST=domain2.tld
    restart: unless-stopped

networks:
  default:
    name: nginx-proxy-network
    external: true
